#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("PagedCarouselPage.Sample.Android.Resource", IsApplication=true)]

namespace PagedCarouselPage.Sample.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Attribute.centered = global::PagedCarouselPage.Sample.Android.Resource.Attribute.centered;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Attribute.clipPadding = global::PagedCarouselPage.Sample.Android.Resource.Attribute.clipPadding;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Attribute.fadeDelay = global::PagedCarouselPage.Sample.Android.Resource.Attribute.fadeDelay;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Attribute.fadeLength = global::PagedCarouselPage.Sample.Android.Resource.Attribute.fadeLength;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Attribute.fades = global::PagedCarouselPage.Sample.Android.Resource.Attribute.fades;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Attribute.fillColor = global::PagedCarouselPage.Sample.Android.Resource.Attribute.fillColor;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Attribute.footerColor = global::PagedCarouselPage.Sample.Android.Resource.Attribute.footerColor;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Attribute.footerIndicatorHeight = global::PagedCarouselPage.Sample.Android.Resource.Attribute.footerIndicatorHeight;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Attribute.footerIndicatorStyle = global::PagedCarouselPage.Sample.Android.Resource.Attribute.footerIndicatorStyle;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Attribute.footerIndicatorUnderlinePadding = global::PagedCarouselPage.Sample.Android.Resource.Attribute.footerIndicatorUnderlinePadding;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Attribute.footerLineHeight = global::PagedCarouselPage.Sample.Android.Resource.Attribute.footerLineHeight;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Attribute.footerPadding = global::PagedCarouselPage.Sample.Android.Resource.Attribute.footerPadding;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Attribute.gapWidth = global::PagedCarouselPage.Sample.Android.Resource.Attribute.gapWidth;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Attribute.linePosition = global::PagedCarouselPage.Sample.Android.Resource.Attribute.linePosition;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Attribute.lineWidth = global::PagedCarouselPage.Sample.Android.Resource.Attribute.lineWidth;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Attribute.pageColor = global::PagedCarouselPage.Sample.Android.Resource.Attribute.pageColor;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Attribute.radius = global::PagedCarouselPage.Sample.Android.Resource.Attribute.radius;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Attribute.selectedBold = global::PagedCarouselPage.Sample.Android.Resource.Attribute.selectedBold;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Attribute.selectedColor = global::PagedCarouselPage.Sample.Android.Resource.Attribute.selectedColor;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Attribute.snap = global::PagedCarouselPage.Sample.Android.Resource.Attribute.snap;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Attribute.strokeColor = global::PagedCarouselPage.Sample.Android.Resource.Attribute.strokeColor;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Attribute.strokeWidth = global::PagedCarouselPage.Sample.Android.Resource.Attribute.strokeWidth;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Attribute.titlePadding = global::PagedCarouselPage.Sample.Android.Resource.Attribute.titlePadding;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Attribute.topPadding = global::PagedCarouselPage.Sample.Android.Resource.Attribute.topPadding;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Attribute.unselectedColor = global::PagedCarouselPage.Sample.Android.Resource.Attribute.unselectedColor;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Attribute.vpiCirclePageIndicatorStyle = global::PagedCarouselPage.Sample.Android.Resource.Attribute.vpiCirclePageIndicatorStyle;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Boolean.default_circle_indicator_centered = global::PagedCarouselPage.Sample.Android.Resource.Boolean.default_circle_indicator_centered;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Boolean.default_circle_indicator_snap = global::PagedCarouselPage.Sample.Android.Resource.Boolean.default_circle_indicator_snap;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Color.default_circle_indicator_fill_color = global::PagedCarouselPage.Sample.Android.Resource.Color.default_circle_indicator_fill_color;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Color.default_circle_indicator_page_color = global::PagedCarouselPage.Sample.Android.Resource.Color.default_circle_indicator_page_color;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Color.default_circle_indicator_stroke_color = global::PagedCarouselPage.Sample.Android.Resource.Color.default_circle_indicator_stroke_color;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Dimension.default_circle_indicator_radius = global::PagedCarouselPage.Sample.Android.Resource.Dimension.default_circle_indicator_radius;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Dimension.default_circle_indicator_stroke_width = global::PagedCarouselPage.Sample.Android.Resource.Dimension.default_circle_indicator_stroke_width;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Id.bottom = global::PagedCarouselPage.Sample.Android.Resource.Id.bottom;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Id.none = global::PagedCarouselPage.Sample.Android.Resource.Id.none;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Id.top = global::PagedCarouselPage.Sample.Android.Resource.Id.top;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Id.triangle = global::PagedCarouselPage.Sample.Android.Resource.Id.triangle;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Id.underline = global::PagedCarouselPage.Sample.Android.Resource.Id.underline;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Integer.default_circle_indicator_orientation = global::PagedCarouselPage.Sample.Android.Resource.Integer.default_circle_indicator_orientation;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.String.library_name = global::PagedCarouselPage.Sample.Android.Resource.String.library_name;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.CirclePageIndicator = global::PagedCarouselPage.Sample.Android.Resource.Styleable.CirclePageIndicator;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.CirclePageIndicator_android_background = global::PagedCarouselPage.Sample.Android.Resource.Styleable.CirclePageIndicator_android_background;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.CirclePageIndicator_android_orientation = global::PagedCarouselPage.Sample.Android.Resource.Styleable.CirclePageIndicator_android_orientation;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.CirclePageIndicator_centered = global::PagedCarouselPage.Sample.Android.Resource.Styleable.CirclePageIndicator_centered;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.CirclePageIndicator_fillColor = global::PagedCarouselPage.Sample.Android.Resource.Styleable.CirclePageIndicator_fillColor;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.CirclePageIndicator_pageColor = global::PagedCarouselPage.Sample.Android.Resource.Styleable.CirclePageIndicator_pageColor;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.CirclePageIndicator_radius = global::PagedCarouselPage.Sample.Android.Resource.Styleable.CirclePageIndicator_radius;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.CirclePageIndicator_snap = global::PagedCarouselPage.Sample.Android.Resource.Styleable.CirclePageIndicator_snap;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.CirclePageIndicator_strokeColor = global::PagedCarouselPage.Sample.Android.Resource.Styleable.CirclePageIndicator_strokeColor;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.CirclePageIndicator_strokeWidth = global::PagedCarouselPage.Sample.Android.Resource.Styleable.CirclePageIndicator_strokeWidth;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.LinePageIndicator = global::PagedCarouselPage.Sample.Android.Resource.Styleable.LinePageIndicator;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.LinePageIndicator_android_background = global::PagedCarouselPage.Sample.Android.Resource.Styleable.LinePageIndicator_android_background;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.LinePageIndicator_centered = global::PagedCarouselPage.Sample.Android.Resource.Styleable.LinePageIndicator_centered;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.LinePageIndicator_gapWidth = global::PagedCarouselPage.Sample.Android.Resource.Styleable.LinePageIndicator_gapWidth;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.LinePageIndicator_lineWidth = global::PagedCarouselPage.Sample.Android.Resource.Styleable.LinePageIndicator_lineWidth;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.LinePageIndicator_selectedColor = global::PagedCarouselPage.Sample.Android.Resource.Styleable.LinePageIndicator_selectedColor;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.LinePageIndicator_strokeWidth = global::PagedCarouselPage.Sample.Android.Resource.Styleable.LinePageIndicator_strokeWidth;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.LinePageIndicator_unselectedColor = global::PagedCarouselPage.Sample.Android.Resource.Styleable.LinePageIndicator_unselectedColor;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.TitlePageIndicator = global::PagedCarouselPage.Sample.Android.Resource.Styleable.TitlePageIndicator;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.TitlePageIndicator_android_background = global::PagedCarouselPage.Sample.Android.Resource.Styleable.TitlePageIndicator_android_background;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.TitlePageIndicator_android_textColor = global::PagedCarouselPage.Sample.Android.Resource.Styleable.TitlePageIndicator_android_textColor;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.TitlePageIndicator_android_textSize = global::PagedCarouselPage.Sample.Android.Resource.Styleable.TitlePageIndicator_android_textSize;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.TitlePageIndicator_clipPadding = global::PagedCarouselPage.Sample.Android.Resource.Styleable.TitlePageIndicator_clipPadding;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.TitlePageIndicator_footerColor = global::PagedCarouselPage.Sample.Android.Resource.Styleable.TitlePageIndicator_footerColor;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.TitlePageIndicator_footerIndicatorHeight = global::PagedCarouselPage.Sample.Android.Resource.Styleable.TitlePageIndicator_footerIndicatorHeight;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.TitlePageIndicator_footerIndicatorStyle = global::PagedCarouselPage.Sample.Android.Resource.Styleable.TitlePageIndicator_footerIndicatorStyle;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.TitlePageIndicator_footerIndicatorUnderlinePadding = global::PagedCarouselPage.Sample.Android.Resource.Styleable.TitlePageIndicator_footerIndicatorUnderlinePadding;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.TitlePageIndicator_footerLineHeight = global::PagedCarouselPage.Sample.Android.Resource.Styleable.TitlePageIndicator_footerLineHeight;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.TitlePageIndicator_footerPadding = global::PagedCarouselPage.Sample.Android.Resource.Styleable.TitlePageIndicator_footerPadding;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.TitlePageIndicator_linePosition = global::PagedCarouselPage.Sample.Android.Resource.Styleable.TitlePageIndicator_linePosition;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.TitlePageIndicator_selectedBold = global::PagedCarouselPage.Sample.Android.Resource.Styleable.TitlePageIndicator_selectedBold;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.TitlePageIndicator_selectedColor = global::PagedCarouselPage.Sample.Android.Resource.Styleable.TitlePageIndicator_selectedColor;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.TitlePageIndicator_titlePadding = global::PagedCarouselPage.Sample.Android.Resource.Styleable.TitlePageIndicator_titlePadding;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.TitlePageIndicator_topPadding = global::PagedCarouselPage.Sample.Android.Resource.Styleable.TitlePageIndicator_topPadding;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.UnderlinePageIndicator = global::PagedCarouselPage.Sample.Android.Resource.Styleable.UnderlinePageIndicator;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.UnderlinePageIndicator_android_background = global::PagedCarouselPage.Sample.Android.Resource.Styleable.UnderlinePageIndicator_android_background;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.UnderlinePageIndicator_fadeDelay = global::PagedCarouselPage.Sample.Android.Resource.Styleable.UnderlinePageIndicator_fadeDelay;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.UnderlinePageIndicator_fadeLength = global::PagedCarouselPage.Sample.Android.Resource.Styleable.UnderlinePageIndicator_fadeLength;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.UnderlinePageIndicator_fades = global::PagedCarouselPage.Sample.Android.Resource.Styleable.UnderlinePageIndicator_fades;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.UnderlinePageIndicator_selectedColor = global::PagedCarouselPage.Sample.Android.Resource.Styleable.UnderlinePageIndicator_selectedColor;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.ViewPagerIndicator = global::PagedCarouselPage.Sample.Android.Resource.Styleable.ViewPagerIndicator;
			global::CaveBirdLabs.Forms.Platform.Android.Resource.Styleable.ViewPagerIndicator_vpiCirclePageIndicatorStyle = global::PagedCarouselPage.Sample.Android.Resource.Styleable.ViewPagerIndicator_vpiCirclePageIndicatorStyle;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int centered = 2130771969;
			
			// aapt resource value: 0x7f01000c
			public const int clipPadding = 2130771980;
			
			// aapt resource value: 0x7f010018
			public const int fadeDelay = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int fadeLength = 2130771993;
			
			// aapt resource value: 0x7f010017
			public const int fades = 2130771991;
			
			// aapt resource value: 0x7f010005
			public const int fillColor = 2130771973;
			
			// aapt resource value: 0x7f01000d
			public const int footerColor = 2130771981;
			
			// aapt resource value: 0x7f010010
			public const int footerIndicatorHeight = 2130771984;
			
			// aapt resource value: 0x7f01000f
			public const int footerIndicatorStyle = 2130771983;
			
			// aapt resource value: 0x7f010011
			public const int footerIndicatorUnderlinePadding = 2130771985;
			
			// aapt resource value: 0x7f01000e
			public const int footerLineHeight = 2130771982;
			
			// aapt resource value: 0x7f010012
			public const int footerPadding = 2130771986;
			
			// aapt resource value: 0x7f01000b
			public const int gapWidth = 2130771979;
			
			// aapt resource value: 0x7f010013
			public const int linePosition = 2130771987;
			
			// aapt resource value: 0x7f01000a
			public const int lineWidth = 2130771978;
			
			// aapt resource value: 0x7f010006
			public const int pageColor = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int radius = 2130771975;
			
			// aapt resource value: 0x7f010014
			public const int selectedBold = 2130771988;
			
			// aapt resource value: 0x7f010002
			public const int selectedColor = 2130771970;
			
			// aapt resource value: 0x7f010008
			public const int snap = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int strokeColor = 2130771977;
			
			// aapt resource value: 0x7f010003
			public const int strokeWidth = 2130771971;
			
			// aapt resource value: 0x7f010015
			public const int titlePadding = 2130771989;
			
			// aapt resource value: 0x7f010016
			public const int topPadding = 2130771990;
			
			// aapt resource value: 0x7f010004
			public const int unselectedColor = 2130771972;
			
			// aapt resource value: 0x7f010000
			public const int vpiCirclePageIndicatorStyle = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f060000
			public const int default_circle_indicator_centered = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int default_circle_indicator_snap = 2131099649;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070000
			public const int default_circle_indicator_fill_color = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int default_circle_indicator_page_color = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int default_circle_indicator_stroke_color = 2131165186;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090000
			public const int default_circle_indicator_radius = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int default_circle_indicator_stroke_width = 2131296257;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int bottom = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int myButton = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int none = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int top = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int triangle = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int underline = 2131034114;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f080000
			public const int default_circle_indicator_orientation = 2131230720;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CirclePageIndicator = new int[] {
					16842948,
					16842964,
					2130771969,
					2130771971,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 1
			public const int CirclePageIndicator_android_background = 1;
			
			// aapt resource value: 0
			public const int CirclePageIndicator_android_orientation = 0;
			
			// aapt resource value: 2
			public const int CirclePageIndicator_centered = 2;
			
			// aapt resource value: 4
			public const int CirclePageIndicator_fillColor = 4;
			
			// aapt resource value: 5
			public const int CirclePageIndicator_pageColor = 5;
			
			// aapt resource value: 6
			public const int CirclePageIndicator_radius = 6;
			
			// aapt resource value: 7
			public const int CirclePageIndicator_snap = 7;
			
			// aapt resource value: 8
			public const int CirclePageIndicator_strokeColor = 8;
			
			// aapt resource value: 3
			public const int CirclePageIndicator_strokeWidth = 3;
			
			public static int[] LinePageIndicator = new int[] {
					16842964,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771978,
					2130771979};
			
			// aapt resource value: 0
			public const int LinePageIndicator_android_background = 0;
			
			// aapt resource value: 1
			public const int LinePageIndicator_centered = 1;
			
			// aapt resource value: 6
			public const int LinePageIndicator_gapWidth = 6;
			
			// aapt resource value: 5
			public const int LinePageIndicator_lineWidth = 5;
			
			// aapt resource value: 2
			public const int LinePageIndicator_selectedColor = 2;
			
			// aapt resource value: 3
			public const int LinePageIndicator_strokeWidth = 3;
			
			// aapt resource value: 4
			public const int LinePageIndicator_unselectedColor = 4;
			
			public static int[] TitlePageIndicator = new int[] {
					16842901,
					16842904,
					16842964,
					2130771970,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 2
			public const int TitlePageIndicator_android_background = 2;
			
			// aapt resource value: 1
			public const int TitlePageIndicator_android_textColor = 1;
			
			// aapt resource value: 0
			public const int TitlePageIndicator_android_textSize = 0;
			
			// aapt resource value: 4
			public const int TitlePageIndicator_clipPadding = 4;
			
			// aapt resource value: 5
			public const int TitlePageIndicator_footerColor = 5;
			
			// aapt resource value: 8
			public const int TitlePageIndicator_footerIndicatorHeight = 8;
			
			// aapt resource value: 7
			public const int TitlePageIndicator_footerIndicatorStyle = 7;
			
			// aapt resource value: 9
			public const int TitlePageIndicator_footerIndicatorUnderlinePadding = 9;
			
			// aapt resource value: 6
			public const int TitlePageIndicator_footerLineHeight = 6;
			
			// aapt resource value: 10
			public const int TitlePageIndicator_footerPadding = 10;
			
			// aapt resource value: 11
			public const int TitlePageIndicator_linePosition = 11;
			
			// aapt resource value: 12
			public const int TitlePageIndicator_selectedBold = 12;
			
			// aapt resource value: 3
			public const int TitlePageIndicator_selectedColor = 3;
			
			// aapt resource value: 13
			public const int TitlePageIndicator_titlePadding = 13;
			
			// aapt resource value: 14
			public const int TitlePageIndicator_topPadding = 14;
			
			public static int[] UnderlinePageIndicator = new int[] {
					16842964,
					2130771970,
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 0
			public const int UnderlinePageIndicator_android_background = 0;
			
			// aapt resource value: 3
			public const int UnderlinePageIndicator_fadeDelay = 3;
			
			// aapt resource value: 4
			public const int UnderlinePageIndicator_fadeLength = 4;
			
			// aapt resource value: 2
			public const int UnderlinePageIndicator_fades = 2;
			
			// aapt resource value: 1
			public const int UnderlinePageIndicator_selectedColor = 1;
			
			public static int[] ViewPagerIndicator = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int ViewPagerIndicator_vpiCirclePageIndicatorStyle = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
